# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Build a Domain Controller
  config.vm.define "dir1" do |dir1|

    # Source box and VM config
    dir1.vm.box = "server-2019.box"
    dir1.vm.guest = "windows"
    dir1.vm.hostname = "DIR1"

    # Network config
    dir1.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
    dir1.vm.network :private_network, ip: "192.168.2.10", gateway: "192.168.2.1"

    # WinRM config
    dir1.vm.communicator = "winrm"
    dir1.winrm.transport = :plaintext
    dir1.winrm.basic_auth_only = true
    dir1.winrm.username = "vagrant"
    dir1.winrm.password = "vagrant"

    # VirtualBox config
    dir1.vm.provider :virtualbox do |v|
      v.gui = true
      v.name = "DIR1"
      v.linked_clone = true
      v.cpus = 1
      v.memory = 2048
    end

    # Install Active Directory
    dir1.vm.provision "shell", path: "./files/install-active-directory.ps1"
    dir1.vm.provision "shell", reboot: true
  
  end

  # Build a generic server
  config.vm.define "srv1" do |srv1|

    # Source box and VM config
    srv1.vm.box = "server-2019.box"
    srv1.vm.guest = "windows"
    srv1.vm.hostname = "SRV1"

    # Network config
    srv1.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
    srv1.vm.network :private_network, ip: "192.168.2.15", gateway: "192.168.2.1"

    # WinRM config
    srv1.vm.communicator = "winrm"
    srv1.winrm.transport = :plaintext
    srv1.winrm.basic_auth_only = true
    srv1.winrm.username = "vagrant"
    srv1.winrm.password = "vagrant"

    # VirtualBox config
    srv1.vm.provider :virtualbox do |v|
      v.gui = true
      v.name = "SRV1"
      v.linked_clone = true
      v.cpus = 2
      v.memory = 2048
    end

    # Join Active Directory
    srv1.vm.provision "shell", path: "./files/join-domain.ps1"
    srv1.vm.provision "shell", reboot: true
  end

  # Build another generic server
  config.vm.define "srv2" do |srv2|

    # Source box and VM config
    srv2.vm.box = "server-2019.box"
    srv2.vm.guest = "windows"
    srv2.vm.hostname = "SRV2"

    # Network config
    srv2.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
    srv2.vm.network :private_network, ip: "192.168.2.16", gateway: "192.168.2.1"

    # WinRM config
    srv2.vm.communicator = "winrm"
    srv2.winrm.transport = :plaintext
    srv2.winrm.basic_auth_only = true
    srv2.winrm.username = "vagrant"
    srv2.winrm.password = "vagrant"

    # VirtualBox config
    srv2.vm.provider :virtualbox do |v|
      v.gui = true
      v.name = "SRV2"
      v.linked_clone = true
      v.cpus = 2
      v.memory = 2048
    end

    # Join Active Directory
    srv2.vm.provision "shell", path: "./files/join-domain.ps1"
    srv2.vm.provision "shell", reboot: true
  end

end